### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/KDFs#13]
For coherence with other crates and other [reasons](https://github.com/sfackler/rust-postgres-macros/issues/19).

Contributor checkoff
----------------------
- [x] @vladikoff (via IRC)
- [x] @warner
- [x] @Ralith

**Comment by Ralith** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by warner** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
