### ISSUE TITLE
expand without extract

### ISSUE THREAD

**Issue by david415** [RustCrypto/KDFs#26]
It would be nice if your API made it easier to perform the expand without the initial extract phase.
This is what I do now:
```
    let hk = Hkdf::<Sha256>{
        prk: *GenericArray::from_slice(prk),
    };
```
Possibly there should be a constructor that does this from_slice method call on the u8 slice.

**Comment by warner** [comment]
Good idea, it looks like #23 will enable that (`hk = Hkdf::<Sha256>::from_prk(prk).unwrap()`).

**Comment by warner** [comment]
Ok #23 is landed, so the next release should have this feature. @david415 wanna confirm that this will work for you?

**Comment by david415** [comment]
@warner yes I have confirmed with a test vector that this change works for my use case.

**Comment by warner** [comment]
Ok, hkdf-0.8.0 is released, I think you should be good to go.
