### ISSUE TITLE
add 0.7.1 tag?

### ISSUE THREAD

**Issue by warner** [RustCrypto/KDFs#27]
It looks like we got an 0.7.1 release on [crates.io](https://crates.io/crates/hkdf/0.7.1) (yay!), but there's no tag on the git repo. The version was updated in 87659b14, but was the release made from that, or from a subsequent commit?

We should compare the crates.io tarball against the last four commits, and add a `hkdf-0.7.1` tag to the right one.

**Comment by newpavlov** [comment]
Small note: in other repositories we use `<crate-name>-v<version>` pattern, e.g. [`sha3-v0.8.2`](https://github.com/RustCrypto/hashes/tree/sha3-v0.8.2).

**Comment by warner** [comment]
Ok, the code is the same as c6a7cb0, and the only subsequent change is in `.travis.yml` which isn't copied into the crate, so the release could have been made from any of fb116d7, ea699af, c6a7cb0, or 87659b1. Given the timestamps in the crate file and commits, I think it was made from fb116d7, so I'm going to add a `hkdf-v0.7.1` tag on that commit.

**Comment by warner** [comment]
One other note: our previous release tags lacked the `v`, so we'll have `hkdf-0.6.0`, `hkdf-0.7.0`, and `hkdf-v0.7.0`. I'm happy to use the `v` going forward, but if anyone objects, tell me quick.

**Comment by warner** [comment]
ok, [done](https://github.com/RustCrypto/KDFs/tree/hkdf-v0.7.1)

**Comment by vladikoff** [comment]
Thank you!!
