### ISSUE TITLE
HKDF: "info" parameter should be Option<&[u8]>

### ISSUE THREAD

**Issue by zer0x64** [RustCrypto/KDFs#30]
As stated by  RFC 5869, the info parameter should be optional. For now, we can technically pass an empty array, but I do believe that using an Option<&[u8]> is more rustic.

I am willing to do a PR if needed.

**Comment by newpavlov** [comment]
In my understanding `None` and `Some(&[])` will have absolutely the same behavior, so I think such API change is redundant. I guess we could introduce something like `expand_noinfo`, but it does not look like it will sufficiently more convenient compared to `h.expand(&[], buf)`. So I propose to close this issue as wontfix.

cc @tarcieri

**Comment by newpavlov** [comment]
Docs updated in this [commit](https://github.com/RustCrypto/KDFs/commit/9dc64c9329b8f8e81df7557735a9825ed3028f0a) (I've made a direct commit by an accident).
