### ISSUE TITLE
hkdf: simplify trait bounds

### ISSUE THREAD

**Issue by newpavlov** [RustCrypto/KDFs#54]
Initially reported in [Zulip](https://rustcrypto.zulipchat.com/#narrow/stream/260043-KDFs/topic/HKDF.20trait.20bounds).

Right now if function uses HKDF and wants to be generic over hash functions, trait bounds look quite scary:
```rust
fn hkdf<H: CoreProxy>()
where
    <H as CoreProxy>::Core: HashMarker
        + UpdateCore
        + FixedOutputCore
        + BufferKindUser<BufferKind = Eager>
        + Default
        + Clone,
    <<H as CoreProxy>::Core as BlockSizeUser>::BlockSize: IsLess<U256>,
    Le<<<H as CoreProxy>::Core as BlockSizeUser>::BlockSize, U256>: NonZero,
{
    Hkdf::<H>::new(None, &[]);
}
```

It could be worth to simplify the bounds somehow. Also it may be worth to allow `hkdf` to use the [`SimpleHmac`](https://docs.rs/hmac/latest/hmac/struct.SimpleHmac.html) in addition to [`Hmac`](https://docs.rs/hmac/latest/hmac/type.Hmac.html). It probably will involve introducing a helper trait or two in `hmac`.

**Comment by jbis9051** [comment]
Since HKDF uses HMAC internally, the trait restrictions for the hash must be the same as the the Hmac crate used.

 As such, this stems from complicated traits here: https://github.com/RustCrypto/MACs/blob/master/hmac/src/optim.rs#L21.

Either that needs to be simplified, or we can use SimpleHmac as in #56 .

**Comment by remoun** [comment]
Another option is to add a `SimpleHkdf` with the same interface/methods, which uses `SimpleHmac` internally. I implemented this in https://github.com/mobilecoinfoundation/KDFs/pull/1

**Comment by newpavlov** [comment]
@remoun 
I considered it, but it would result in a significant amount of code duplication, so I don't think it will be an improvement over the approach in #57.
