### ISSUE TITLE
Concatenation and ASN.1 KDFs

### ISSUE THREAD

**Issue by rpiasetskyi** [RustCrypto/KDFs#58]
Would it make sense to have a Concatenation and ASN.1 KDFs in this repository?
These key derivation functions are described in [NIST SP 800-56A 5.8.1 and 5.8.2](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-56ar.pdf#page=47).

If these functions suit this repository, I would like to offer my help (implementation).

**Comment by tarcieri** [comment]
Sure, sounds interesting.

Related: https://github.com/RustCrypto/formats/tree/master/der
