### ISSUE TITLE
Move rust-hkdf under the RustCrypto org

### ISSUE THREAD

**Issue by vladikoff** [RustCrypto/KDFs#6]
@warner do we still want to do this? Let me know!

P.S. version 0.2.0 is live.

**Comment by warner** [comment]
I think so. Lemme check with the RustCrypto folks and see what the plan should be. I think they may need to add a `kdfs` repo, and some traits, so there's a question of what other KDFs we could imagine adding, and what their common API might be. I'll file an issue on their `traits` repo and see what they think.

**Comment by vladikoff** [comment]
Sounds good! 👍

**Comment by newpavlov** [comment]
Sorry for the late response!

I think the most appropriate course of action will be the following:
- Transfer this repository to the RustCrypto org (to save commit history)
- I will rename repository to RustCrypto/KDFs and will move code to the hkdf folder
- If you are interested I'll invite you to the org and will provide full access to KDFs repo (additional maintainers are always welcomed  :) )
- You'll provide access to hkdf crate on crates.io either to me directly or to the RustCrypto:admins group

As for traits, as discussed in the RustCrypto/traits#5, I think for now we can proceed without traits until we'll get more KDF and password hashing functions.

**Comment by vladikoff** [comment]
> Transfer this repository to the RustCrypto org (to save commit history)

This sounds good to me 👍 

> I will rename repository to RustCrypto/KDFs and will move code to the hkdf folder

👍 , will that folder keep the cargo file? (will the crate be published separately?)

> If you are interested I'll invite you to the org and will provide full access to KDFs repo (additional maintainers are always welcomed :) )

That would be great, in past projects I've created scoped teams, so maybe a `RustCrypto:hkdf-team` or something would be great for @warner and me.

> You'll provide access to hkdf crate on crates.io either to me directly or to the RustCrypto:admins group

Sounds good. Let me know if there is some Slack-IRC-Gitter system you use so we can use it to make this change smooth.

**Comment by newpavlov** [comment]
I've sent invites to both of you.

>will that folder keep the cargo file? (will the crate be published separately?)

The new repo will repeat the folder structure of other RustCrypto repositories, i.e. `rust-hkdf/Cargo.toml` will move to `KDFs/hkdf/Cargo.toml`, while `KDFs/Cargo.toml` will be a [virtual manifest](https://github.com/RustCrypto/hashes/blob/master/Cargo.toml).

Crate will be published separately from other crates and process will be essentially the same as right now.

>Sounds good. Let me know if there is some Slack-IRC-Gitter system you use so we can use it to make this change smooth.

I and @tarcieri are usually available in the [#rust-crypto](https://chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-crypto) IRC channel.

**Comment by newpavlov** [comment]
Done. :)
